create database if not exists back_scan;
use back_scan;
CREATE TABLE IF NOT EXISTS `CONTRACT_LOG_CS` (
`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`CONTRACT_LOG_ID` char(32) NOT NULL,
`TRANS_TIME` bigint(20) NOT NULL,
`TRANS_TYPE` varchar(4) NOT NULL,
`CHANNEL` varchar(10) NOT NULL,
`RESULT` tinyint(4) NOT NULL,
`ERROR_CODE` varchar(20) DEFAULT NULL,
`ERROR_MESSAGE` varchar(14000) DEFAULT NULL,
`CONTRACT_NO` varchar(30) DEFAULT NULL,
`USER_ID` varchar(32) NOT NULL,
`USER_NAME` varchar(150) NOT NULL,
`IDENT_NO` varchar(150) NOT NULL,
`USER_TYPE` tinyint(4) NOT NULL,
`OPERATOR_NAME` varchar(150) NOT NULL,
`OPERATOR_IDENT_NO` varchar(150) NOT NULL,
`URI` varchar(150) NOT NULL,
`DATA` mediumtext NOT NULL,
`SIGNATURE` varchar(14000) NOT NULL,
`EXCEPTION_MESSAGE` text DEFAULT NULL,
`COST_TIME` int(10) DEFAULT '0',
PRIMARY KEY (`ID`),
UNIQUE KEY `contract_log_id` (`CONTRACT_LOG_ID`),
KEY `cno_idx` (`CONTRACT_NO`),
KEY `com_idx2` (`TRANS_TYPE`,`RESULT`,`TRANS_TIME`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=87782901;